import {Select} from '../components/Select';
import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../contexts/AuthContext';
import './agenda.css';
function localParts(d:Date,zone:string){
 const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).map(p=>[p.type,p.value]));
 return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`};
}
function weeklyDates(weekday:number,start:string,end:string,zone:string){
 const today=localParts(new Date(),zone).date;const d=new Date(today+'T00:00:00Z');
 d.setUTCDate(d.getUTCDate()+(weekday-d.getUTCDay()+7)%7);const date=d.toISOString().slice(0,10);
 const utc=(time:string)=>{const guess=Date.parse(date+'T'+time+':00Z');const parts=localParts(new Date(guess),zone);const offset=Date.parse(parts.date+'T'+parts.time+':00Z')-guess;return new Date(guess-offset).toISOString();};
 return {startDate:utc(start),endDate:utc(end)};
}
const DAYS=["Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu"];
interface Agenda { hasImage?:boolean; topic?:string; speakerName?:string; speakerRole?:string; audience?:string; invitation?:string; quote?:string;  repeatWeekly?:boolean; id:string; title:string; description?:string; startDate:string; endDate?:string; location?:string; isActive:boolean }
function Icon({name}:{name:string}) {const paths:Record<string,string>={calendar:'M4 5h16v16H4ZM8 3v4m8-4v4M4 10h16m-12 4h2m4 0h2m-8 3h2',pin:'M12 22s8-9 8-14a8 8 0 0 0-16 0c0 5 8 14 8 14ZM12 5a3 3 0 1 0 0 6 3 3 0 0 0 0-6',file:'M5 3h10l4 4v14H5Zm10 0v5h4M9 12h6m-6 4h6',edit:'m4 16 12-12 4 4L8 20H4Zm10-10 4 4',trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 4v5l3 2'};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>}
export function AgendaPage(){
 const {user}=useAuth();
 const emptyDetails={topic:'',speakerName:'',speakerRole:'',audience:'',invitation:'',quote:''};
 const [imageFile,setImageFile]=useState<File|null>(null),[savedImage,setSavedImage]=useState(false),[removeImage,setRemoveImage]=useState(false),[preview,setPreview]=useState('');
 useEffect(()=>{if(!imageFile){setPreview('');return;}const url=URL.createObjectURL(imageFile);setPreview(url);return()=>URL.revokeObjectURL(url);},[imageFile]);
 const [details,setDetails]=useState(emptyDetails);
 const [items,setItems]=useState<Agenda[]>([]),[editing,setEditing]=useState<string|null>(null);
 const [title,setTitle]=useState(''),[startDate,setStartDate]=useState(''),[location,setLocation]=useState(''),[description,setDescription]=useState('');
 const [startTime,setStartTime]=useState('07:00'),[endTime,setEndTime]=useState('07:45');
 const [repeatWeekly,setRepeatWeekly]=useState(false),[weekday,setWeekday]=useState(4),[endDate,setEndDate]=useState('');
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const [clock,setClock]=useState(new Date()),[timezone,setTimezone]=useState('Asia/Jakarta');
 const load=()=>api.get<Agenda[]>('/agendas').then(setItems).catch(err=>setError(err.message));
 useEffect(()=>{void load();api.get<{timezone:string}>('/mosque').then(m=>setTimezone(m.timezone)).catch(()=>{});const timer=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(timer)},[]);
 const reset=()=>{setImageFile(null);setSavedImage(false);setRemoveImage(false);setDetails(emptyDetails);setEditing(null);setTitle('');setStartDate('');setLocation('');setDescription('');setRepeatWeekly(false);setEndDate('');setWeekday(4);setStartTime('07:00');setEndTime('07:45')};
 const edit=(a:Agenda)=>{setImageFile(null);setSavedImage(!!a.hasImage);setRemoveImage(false);setDetails({topic:a.topic||'',speakerName:a.speakerName||'',speakerRole:a.speakerRole||'',audience:a.audience||'',invitation:a.invitation||'',quote:a.quote||''});const d=new Date(a.startDate);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);setRepeatWeekly(!!a.repeatWeekly);setWeekday(new Date(localParts(d,timezone).date).getUTCDay());setStartTime(localParts(d,timezone).time);setEndTime(a.endDate?localParts(new Date(a.endDate),timezone).time:'07:45');setEndDate(a.endDate?new Date(new Date(a.endDate).getTime()-new Date(a.endDate).getTimezoneOffset()*60000).toISOString().slice(0,16):'');setEditing(a.id);setTitle(a.title);setStartDate(local);setLocation(a.location||'');setDescription(a.description||'');setError('');setMessage('');window.scrollTo({top:0,behavior:'smooth'})};
 const onSubmit=async(e:React.FormEvent)=>{e.preventDefault();if(!title.trim()){setError('Isi judul agenda.');return}if(!repeatWeekly&&endDate&&new Date(endDate)<=new Date(startDate)){setError('Waktu selesai harus setelah waktu mulai.');return}if(repeatWeekly&&(!startTime||!endTime||endTime<=startTime)){setError('Jam selesai harus setelah jam mulai pada hari yang sama.');return}setBusy(true);setError('');setMessage('');try{const payload={...details,title:title.trim(),...(repeatWeekly?weeklyDates(weekday,startTime,endTime,timezone):{startDate:new Date(startDate).toISOString(),endDate:endDate?new Date(endDate).toISOString():null}),repeatWeekly,location,description};const saved=editing?await api.patch<Agenda>(`/agendas/${editing}`,payload):await api.post<Agenda>('/agendas',payload);setEditing(saved.id);if(imageFile){const data=new FormData();data.append('file',imageFile);try{await api.upload(`/agendas/${saved.id}/image`,data);}catch(e){await load();throw new Error('Agenda tersimpan, tetapi gambar gagal diupload. Klik Simpan Perubahan untuk mencoba lagi. '+(e as Error).message);}}else if(removeImage){await api.delete(`/agendas/${saved.id}/image`);}setMessage(editing?'Perubahan agenda tersimpan.':'Agenda berhasil ditambahkan.');reset();await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}};
 const mutate=async(a:Agenda,remove=false)=>{if(remove&&!confirm(`Hapus agenda "${a.title}"?`))return;setBusy(true);setError('');try{if(remove){await api.delete(`/agendas/${a.id}`);if(editing===a.id)reset()}else await api.patch(`/agendas/${a.id}`,{isActive:!a.isActive});await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}};
 const day=(date:string|Date)=>new Date(date).toLocaleDateString('en-CA',{timeZone:timezone});
 const shown=items.filter(a=>[a.title,a.description,a.location].join(' ').toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='today'?day(a.startDate)===day(clock):filter==='upcoming'?Date.parse(a.endDate||a.startDate)>=clock.getTime():Date.parse(a.endDate||a.startDate)<clock.getTime())));
 return <div className="agenda-page"><header className="agenda-header"><div><small>CONTENT</small><h1>Agenda Kegiatan</h1><p>Kelola agenda kegiatan masjid yang akan ditampilkan pada layar informasi.</p></div><div className="agenda-date"><Icon name="calendar"/><div><b>{clock.toLocaleDateString('id-ID',{timeZone:timezone,weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><small>{clock.toLocaleDateString('id-ID-u-ca-islamic',{timeZone:timezone,day:'numeric',month:'long',year:'numeric'})}</small></div></div><strong className="agenda-clock">{clock.toLocaleTimeString('id-ID',{timeZone:timezone,hourCycle:'h23'}).replaceAll('.',':')}</strong><div className="agenda-account"><span>{user?.name?.charAt(0)}</span><div><b>{user?.name}</b><small>● Sesi aktif</small></div></div></header>
 {error&&<div className="alert-error" role="alert">{error}</div>}{message&&<div className="alert-success" role="status">{message}</div>}
 <form className="form-panel agenda-form" onSubmit={onSubmit}><div className="agenda-panel-title"><Icon name="calendar"/><div><h2>{editing?'Edit Agenda Kegiatan':'Tambah Agenda Kegiatan'}</h2><p>Tambahkan agenda baru yang akan ditampilkan pada layar masjid.</p></div></div>
 <div className="form-row"><label>Pengulangan<Select value={repeatWeekly?'weekly':'once'} onChange={e=>setRepeatWeekly(e.target.value==='weekly')}><option value="once">Sekali saja</option><option value="weekly">Setiap minggu</option></Select></label>{repeatWeekly&&<label>Hari kegiatan<Select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{DAYS.map((d,i)=><option key={d} value={i}>{d}</option>)}</Select></label>}</div>
 <div className="form-row"><label>Judul Agenda <em>*</em><div className="agenda-input"><Icon name="file"/><input placeholder="Contoh: Kajian Rutin, Pengajian, Kerja Bakti, dll" value={title} onChange={e=>setTitle(e.target.value)} required/></div></label><label>{repeatWeekly?'Jam mulai':'Tanggal & jam mulai'} <em>*</em><div className="agenda-input"><Icon name="calendar"/><input type={repeatWeekly?"time":"datetime-local"} value={repeatWeekly?startTime:startDate} onChange={e=>repeatWeekly?setStartTime(e.target.value):setStartDate(e.target.value)} required/></div></label><label>{repeatWeekly?'Jam selesai':'Tanggal & jam selesai'}{repeatWeekly&&<em>*</em>}<div className="agenda-input"><Icon name="clock"/><input type={repeatWeekly?"time":"datetime-local"} value={repeatWeekly?endTime:endDate} min={repeatWeekly?startTime:startDate} onChange={e=>repeatWeekly?setEndTime(e.target.value):setEndDate(e.target.value)} required={repeatWeekly}/></div></label><label>Lokasi Kegiatan<div className="agenda-input"><Icon name="pin"/><input placeholder="Contoh: Mushola, Aula, Lantai 2, dll" value={location} onChange={e=>setLocation(e.target.value)}/></div></label><label>Deskripsi<div className="agenda-input"><Icon name="file"/><textarea placeholder="Tuliskan deskripsi agenda di sini..." value={description} onChange={e=>setDescription(e.target.value)} rows={2}/></div></label></div>
 <section style={{margin:'18px 0'}}><label>Gambar Kajian<input key={editing||'new'} type="file" accept=".png,.jpg,.jpeg,.webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setError('Ukuran gambar maksimal 5 MB.');e.target.value='';return;}setImageFile(f);setRemoveImage(false);}}/></label><p className="hint">PNG, JPG, WebP, maksimal 5 MB. Gambar vertikal cocok untuk panel kiri. Perubahan diterapkan setelah agenda disimpan.</p>{(preview||(savedImage&&!removeImage))&&<img src={preview||`${api.baseUrl}/agendas/${editing}/image?v=${editing}`} alt="Preview gambar kajian" style={{width:160,height:200,objectFit:'cover',borderRadius:12}}/>}<button type="button" className="secondary" disabled={busy} onClick={()=>{setImageFile(null);setRemoveImage(true);}}>Gunakan Gambar Bawaan</button></section>
 <details className="agenda-extra" open><summary>Informasi Kajian untuk Display (opsional)</summary><div className="form-row">{([['topic','Topik kajian'],['speakerName','Nama pemateri'],['speakerRole','Keterangan pemateri'],['audience','Peserta / ditujukan untuk'],['invitation','Ajakan hadir'],['quote','Kutipan / pesan']] as const).map(([key,label])=><label key={key}>{label}<input maxLength={300} value={details[key]} onChange={e=>setDetails({...details,[key]:e.target.value})}/></label>)}</div><p className="hint">Judul agenda menjadi judul utama. Deskripsi menjadi penjelasan materi. Kosongkan pemateri bila belum ditentukan.</p></details>
 <p className="hint">{repeatWeekly?`Berulang setiap ${DAYS[weekday]}, pukul ${startTime}?${endTime} (${timezone}). Tidak perlu memilih tanggal.`:`Waktu input mengikuti zona waktu komputer (${Intl.DateTimeFormat().resolvedOptions().timeZone}). Daftar ditampilkan dalam ${timezone}.`}</p><div className="form-actions"><button disabled={busy} type="submit">{busy?'Menyimpan...':editing?'Simpan Perubahan':'+ Tambah Agenda'}</button>{editing&&<button type="button" className="secondary" disabled={busy} onClick={reset}>Batal</button>}</div></form>
 <section className="form-panel agenda-list"><div className="agenda-list-heading"><div className="agenda-panel-title"><Icon name="calendar"/><div><h2>Daftar Agenda Kegiatan</h2><p>Agenda aktif ditampilkan pada layar informasi sesuai jadwal.</p></div></div><div className="agenda-filters"><div className="agenda-input"><Icon name="search"/><input aria-label="Cari agenda" placeholder="Cari agenda..." value={query} onChange={e=>setQuery(e.target.value)}/></div><Select aria-label="Filter tanggal agenda" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua Tanggal</option><option value="today">Hari Ini</option><option value="upcoming">Akan Datang / Berlangsung</option><option value="past">Sudah Lewat</option></Select></div></div>
 <div className="agenda-table-scroll"><table className="data-table"><thead><tr>{['No','Judul Agenda','Tanggal & Waktu','Lokasi','Deskripsi','Status','Aksi'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((a,i)=><tr key={a.id}><td>{i+1}</td><td><div className="agenda-name"><span className={`agenda-item-icon tone-${i%3}`}><Icon name="file"/></span><b>{a.title}</b></div></td><td>{a.repeatWeekly&&<strong>Setiap {new Date(a.startDate).toLocaleDateString('id-ID',{timeZone:timezone,weekday:'long'})}<br/></strong>}<div className="agenda-date-cell"><Icon name="calendar"/>{new Date(a.startDate).toLocaleDateString('id-ID',{timeZone:timezone,weekday:'short',day:'numeric',month:'short',year:'numeric'})}</div><div className="agenda-date-cell"><Icon name="clock"/>{new Date(a.startDate).toLocaleTimeString('id-ID',{timeZone:timezone,hour:'2-digit',minute:'2-digit'})}{a.endDate&&` – ${new Date(a.endDate).toLocaleTimeString('id-ID',{timeZone:timezone,hour:'2-digit',minute:'2-digit'})}`}</div></td><td>{a.location||'—'}</td><td className="agenda-description">{a.description||'—'}</td><td><button disabled={busy} className={`agenda-status ${a.isActive?'active':'inactive'}`} onClick={()=>mutate(a)} aria-label={`${a.isActive?'Nonaktifkan':'Aktifkan'} ${a.title}`}>{a.isActive?'Aktif':'Nonaktif'}</button></td><td><div className="agenda-actions"><button className="secondary" disabled={busy} onClick={()=>edit(a)} title="Edit agenda" aria-label={`Edit ${a.title}`}><Icon name="edit"/></button><button className="danger" disabled={busy} onClick={()=>mutate(a,true)} title="Hapus agenda" aria-label={`Hapus ${a.title}`}><Icon name="trash"/></button></div></td></tr>)}{!shown.length&&<tr><td colSpan={7}>{items.length?'Tidak ada agenda yang sesuai pencarian.':'Belum ada agenda. Tambahkan melalui form di atas.'}</td></tr>}</tbody></table></div></section></div>;
}
