import {Select} from '../components/Select';
import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../contexts/AuthContext';
import './content.css';
interface Content {id:string;type:string;title?:string;content?:string;mediaUrl?:string;displayOrder:number;isActive:boolean}
const TYPES:Record<string,string>={ANNOUNCEMENT:'Pengumuman',QURAN:'Ayat Al-Quran',HADITH:'Hadits',IMAGE:'Gambar / Poster',VIDEO:'Video',RUNNING_TEXT:'Teks Berjalan'};
function Preview({type,title,body,url}:{type:string;title:string;body:string;url:string}){return <div className="content-preview-scene">{type==='IMAGE'&&url?<img className="content-preview-media" src={url} alt={title||'Preview gambar'}/>:type==='VIDEO'&&url?<video className="content-preview-media" controls preload="metadata" src={url}/>:<><img className="content-preview-logo" src="/mosque-logo.svg" alt=""/><strong>{title||'Preview Konten'}</strong><p>{body||'Konten Anda akan tampil di sini'}</p></>}</div>}
export function ContentPage(){
 const {user}=useAuth();const [items,setItems]=useState<Content[]>([]),[type,setType]=useState('ANNOUNCEMENT'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[mediaUrl,setMediaUrl]=useState(''),[order,setOrder]=useState(0),[editing,setEditing]=useState<string|null>(null);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(1),[preview,setPreview]=useState<Content|null>(null),[clock,setClock]=useState(new Date()),[timezone,setTimezone]=useState('Asia/Jakarta');
 const load=()=>api.get<Content[]>('/contents').then(setItems).catch(e=>setError(e.message));
 useEffect(()=>{void load();api.get<{timezone:string}>('/mosque').then(m=>setTimezone(m.timezone)).catch(()=>{});const timer=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(timer)},[]);
 const reset=()=>{setEditing(null);setTitle('');setBody('');setMediaUrl('');setOrder(0);setPreview(null)};
 const edit=(c:Content)=>{setEditing(c.id);setType(c.type);setTitle(c.title||'');setBody(c.content||'');setMediaUrl(c.mediaUrl||'');setOrder(c.displayOrder);setPreview(null);setMessage('');setError('');window.scrollTo({top:0,behavior:'smooth'})};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const data={type,title:title.trim(),content:body,mediaUrl:['IMAGE','VIDEO'].includes(type)?mediaUrl:'',displayOrder:order};if(editing)await api.patch(`/contents/${editing}`,data);else await api.post('/contents',data);reset();await load();setMessage('Konten berhasil disimpan.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const action=async(c:Content,remove=false)=>{if(remove&&!confirm(`Hapus konten "${c.title||TYPES[c.type]}"?`))return;setBusy(true);setError('');try{if(remove){await api.delete(`/contents/${c.id}`);if(editing===c.id)reset();if(preview?.id===c.id)setPreview(null)}else await api.patch(`/contents/${c.id}`,{isActive:!c.isActive});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const filtered=items.filter(c=>(!filter||c.type===filter)&&[c.title,c.content].join(' ').toLowerCase().includes(query.toLowerCase()));const totalPages=Math.max(1,Math.ceil(filtered.length/5));const current=Math.min(page,totalPages);const shown=filtered.slice((current-1)*5,current*5);const isMedia=['IMAGE','VIDEO'].includes(type);
 return <div className="content-page"><header><div><small>▣ CONTENT</small><h1>Konten Display</h1><p>Kelola konten yang ditampilkan pada layar display masjid.</p></div><div className="content-header-date"><b>{clock.toLocaleDateString('id-ID',{timeZone:timezone,weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><small>{clock.toLocaleDateString('id-ID-u-ca-islamic',{timeZone:timezone,day:'numeric',month:'long',year:'numeric'})}</small></div><strong className="content-clock">{clock.toLocaleTimeString('id-ID',{timeZone:timezone,hourCycle:'h23'}).replaceAll('.',':')}</strong><div className="content-user"><b>{user?.name}</b><small>● Sesi aktif</small></div></header>
 {error&&<div className="alert-error" role="alert">{error}</div>}{message&&<div className="alert-success" role="status">{message}</div>}
 <div className="content-top"><form className="form-panel" onSubmit={submit}><div className="content-panel-heading"><span>▧</span><div><h2>{editing?'Edit Konten Display':'Tambah Konten Display'}</h2><p>Kelola konten yang akan ditampilkan pada layar masjid.</p></div></div><div className="form-row"><label>Jenis Konten<Select value={type} onChange={e=>{setType(e.target.value);setPreview(null)}}>{Object.entries(TYPES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></label><label>Judul Konten<input required placeholder="Contoh: Kajian Rutin, Pengumuman, dll" value={title} onChange={e=>{setTitle(e.target.value);setPreview(null)}}/></label><label>{isMedia?'URL File Konten':'Isi Konten'}{isMedia?<input type="url" required placeholder={type==='IMAGE'?'https://.../poster.jpg':'https://.../video.mp4'} value={mediaUrl} onChange={e=>{setMediaUrl(e.target.value);setPreview(null)}}/>:<textarea required placeholder="Tuliskan isi konten di sini..." value={body} onChange={e=>{setBody(e.target.value);setPreview(null)}} rows={2}/>}</label><label>Urutan Tampilan<input type="number" min={0} required value={order} onChange={e=>setOrder(Number(e.target.value))}/><small>Angka lebih kecil ditampilkan lebih dahulu.</small></label></div>{isMedia&&<p className="hint">Gunakan URL langsung ke gambar/video yang dapat diakses perangkat display. Upload file dan pengaturan durasi belum tersedia.</p>}<div className="form-actions"><button disabled={busy} type="submit">{busy?'Menyimpan...':editing?'Simpan Perubahan':'+ Tambah Konten'}</button>{editing&&<button type="button" className="secondary" disabled={busy} onClick={reset}>Batal</button>}</div></form><section className="form-panel content-preview"><div className="content-panel-heading"><span>▣</span><div><h2>Preview Konten</h2><p>Pratinjau gambar, video, atau teks.</p></div></div><Preview type={preview?.type||type} title={preview?.title||title} body={preview?.content||body} url={preview?.mediaUrl||mediaUrl}/><div className="content-preview-dots">{items.slice(0,4).map(c=><button key={c.id} aria-label={`Preview ${c.title||TYPES[c.type]}`} className={preview?.id===c.id?'selected':''} onClick={()=>setPreview(c)}/>)}</div></section></div>
 <div className="content-bottom"><section className="form-panel"><div className="content-list-heading"><div className="content-panel-heading"><span>▧</span><div><h2>Daftar Konten Display</h2><p>Atur status dan urutan konten layar informasi.</p></div></div><div className="content-filters"><input aria-label="Cari konten" placeholder="Cari konten..." value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><Select aria-label="Filter jenis konten" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="">Semua Jenis</option>{Object.entries(TYPES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></div></div><div className="content-table-scroll"><table className="data-table"><thead><tr>{['No','Thumbnail','Judul Konten','Jenis','Status','Urutan','Aksi'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((c,i)=><tr key={c.id}><td>{(current-1)*5+i+1}</td><td><button className="content-thumbnail" aria-label={`Preview ${c.title||TYPES[c.type]}`} onClick={()=>setPreview(c)}>{c.type==='IMAGE'&&c.mediaUrl?<img src={c.mediaUrl} alt="" loading="lazy"/>:<span>{c.type==='VIDEO'?'▷':'▤'}</span>}</button></td><td><b>{c.title||'Tanpa judul'}</b><small className="content-excerpt">{c.content||'Media display'}</small></td><td><span className="content-type">{TYPES[c.type]||c.type}</span></td><td><button disabled={busy} className={`content-status ${c.isActive?'active':''}`} onClick={()=>action(c)}>{c.isActive?'Aktif':'Nonaktif'}</button></td><td>{c.displayOrder}</td><td><div className="content-actions"><button className="secondary" disabled={busy} onClick={()=>edit(c)}>Edit</button><button className="danger" disabled={busy} onClick={()=>action(c,true)}>Hapus</button></div></td></tr>)}{!shown.length&&<tr><td colSpan={7}>Belum ada konten yang sesuai.</td></tr>}</tbody></table></div><div className="content-pagination"><span>{filtered.length?`Menampilkan ${(current-1)*5+1}–${Math.min(current*5,filtered.length)} dari ${filtered.length} konten`:'0 konten'}</span><div><button className="secondary" disabled={current===1} onClick={()=>setPage(current-1)} aria-label="Halaman sebelumnya">‹</button><b>{current}</b><button className="secondary" disabled={current===totalPages} onClick={()=>setPage(current+1)} aria-label="Halaman berikutnya">›</button></div></div></section><aside className="content-tips"><h3>♧ Tips Konten Display</h3><ol><li>Gunakan gambar beresolusi 1920 × 1080 agar jelas pada TV.</li><li>Pastikan URL media dapat dibuka dari perangkat display.</li><li>Klik thumbnail untuk melihat preview konten.</li><li>Edit urutan untuk menentukan prioritas tampilan.</li><li>Nonaktifkan konten yang sudah tidak digunakan.</li></ol></aside></div></div>;
}
