import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import { getRealtimeSocket } from '../lib/socket';
import { useAuth } from '../contexts/AuthContext';
import './dashboard.css';
interface Prayer { date: string; effective: Record<string,string>; nextPrayer: {name:string;label:string;date:string;atUtc:string}|null; stale?:boolean }
interface Player {id:string;name:string;online:boolean;status:string}
interface Agenda {id:string;title:string;startDate:string;endDate?:string;location?:string}
interface Content {id:string;title?:string;type:string}
interface History {id:string;audioName?:string;status:string;startedAt:string}
interface Schedule {id:string;audio?:{name:string}}
interface Upcoming {items:{id:string;atUtc:string|null}[]}
interface Mosque {name:string;city?:string;timezone:string}
const PRAYERS=[['fajr','Subuh','sunrise'],['dhuhr','Dzuhur','sun'],['asr','Ashar','cloud'],['maghrib','Maghrib','sunset'],['isha','Isya','moon']];
const STATUS:Record<string,string>={FINISHED:'Selesai',PLAYING:'Diputar',ERROR:'Gagal',STOPPED:'Dihentikan',QUEUED:'Antrean'};
export function DashboardIcon({name}:{name:string}) {return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name==='sun'?<><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/></>:name==='moon'?<path d="M20 15A9 9 0 0 1 9 3a9 9 0 1 0 11 12Z"/>:name==='cloud'?<path d="M6 19a4 4 0 0 1-1-8 6 6 0 0 1 11-3 5.5 5.5 0 1 1 2 11Z"/>:name==='sunrise'||name==='sunset'?<><path d="M3 18h18M5 21h14M6 15a6 6 0 0 1 12 0M12 2v3M3 7l2 2m14 0 2-2"/></>:name==='audio'?<path d="m3 9 4 0 5-4v14l-5-4H3ZM16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>:name==='calendar'?<><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 4h1m6 0h1m-8 3h1"/></>:name==='clock'?<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h6m-6 5h6m-6 5h4"/></>}</svg>}
export function DashboardPage(){
 const {user}=useAuth();
 const [data,setData]=useState<{mosque:Mosque;prayer:Prayer;players:Player[];agendas:Agenda[];contents:Content[];history:History[];schedules:Schedule[];upcoming:Upcoming}|null>(null);
 const [error,setError]=useState(''),[clock,setClock]=useState(new Date());
 useEffect(()=>{let disposed=false,loading=false;const load=async()=>{if(loading)return;loading=true;try{const [mosque,prayer,players,agendas,contents,history,schedules,upcoming]=await Promise.all([api.get<Mosque>('/mosque'),api.get<Prayer>('/prayers/today'),api.get<Player[]>('/players'),api.get<Agenda[]>('/agendas?activeOnly=true'),api.get<Content[]>('/contents?activeOnly=true'),api.get<History[]>('/history'),api.get<Schedule[]>('/audio-schedules'),api.get<Upcoming>('/audio-schedules/upcoming')]);if(!disposed){setData({mosque,prayer,players,agendas,contents,history,schedules,upcoming});setError('')}}catch(err){if(!disposed)setError((err as Error).message)}finally{loading=false}};void load();const poll=setInterval(load,20000),tick=setInterval(()=>setClock(new Date()),1000);const socket=getRealtimeSocket();const events=['player:status','playback:update','mosque:updated','content:updated'];events.forEach(e=>socket.on(e,load));return()=>{disposed=true;clearInterval(poll);clearInterval(tick);events.forEach(e=>socket.off(e,load))}},[]);
 const timezone=data?.mosque.timezone||'Asia/Jakarta';
 const dateKey=(date:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
 const today=dateKey(clock), time=(value:string)=>new Date(value).toLocaleTimeString('id-ID',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
 const agendas=(data?.agendas||[]).filter(a=>dateKey(new Date(a.startDate))<=today&&dateKey(new Date(a.endDate||a.startDate))>=today).sort((a,b)=>a.startDate.localeCompare(b.startDate));
 const online=data?.players.filter(p=>p.online).length||0,next=data?.prayer.nextPrayer;
 const seconds=next?Math.max(0,Math.ceil((Date.parse(next.atUtc)-clock.getTime())/1000)):null;
 const countdown=seconds===null?['--','--','--']:[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0'));
 const upcoming=(data?.upcoming.items||[]).filter(i=>i.atUtc).sort((a,b)=>a.atUtc!.localeCompare(b.atUtc!)).slice(0,5);
 return <div className="dashboard-v2">
 <header className="dash-header"><div><h1>Assalamu'alaikum, {user?.name||'Admin'} <span>☀</span></h1><p>Selamat datang di panel pengelolaan mushola. Semoga dimudahkan dalam amanah ini.</p></div><div className="dash-date"><DashboardIcon name="calendar"/><div><b>{clock.toLocaleDateString('id-ID',{timeZone:timezone,weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><small>{clock.toLocaleDateString('id-ID-u-ca-islamic',{timeZone:timezone,day:'numeric',month:'long',year:'numeric'})}</small></div></div><strong className="dash-clock">{clock.toLocaleTimeString('id-ID',{timeZone:timezone,hourCycle:'h23'}).replaceAll('.',':')}</strong><div className="dash-account"><span>{user?.name?.charAt(0)||'A'}</span><div><b>{user?.name}</b><small>● Sesi aktif</small></div></div></header>
 {error&&<div className="alert-error" role="alert">Pembaruan data gagal: {error}{data&&' Data terakhir ditampilkan.'}</div>}
 {!data&&!error&&<p className="hint">Memuat ringkasan dashboard...</p>}
 <div className="dash-overview"><section className="dash-prayer-hero"><div className="dash-hero-photo"/><div className="dash-hero-copy"><small>SHOLAT BERIKUTNYA</small><h2>{next?.label||'Menunggu jadwal'}</h2><div className="dash-countdown">{countdown.map((part,i)=><React.Fragment key={i}>{i>0&&<i>:</i>}<div><b>{part}</b><small>{['JAM','MENIT','DETIK'][i]}</small></div></React.Fragment>)}</div><p>“Dirikanlah sholat, sesungguhnya sholat mencegah dari perbuatan keji dan mungkar.”<br/><span>(QS. Al-'Ankabut: 45)</span></p>{data?.prayer.stale&&<small>Jadwal cadangan — periksa koneksi API</small>}</div></section>
 <section className="dash-stat"><span className="dash-stat-icon green"><DashboardIcon name="audio"/></span><h2>Status Player</h2><strong>{data?`${online} / ${data.players.length}`:'—'} <span>Online</span></strong><div className="dash-stat-list">{data?.players.slice(0,2).map(p=><p key={p.id}><i className={p.online?'dot online':'dot'}/><span>{p.name}<small>{p.online?'Online':'Offline'} · {p.status}</small></span></p>)}{data&&!data.players.length&&<p>Belum ada player terdaftar.</p>}</div><Link to="/players">Lihat Detail</Link></section>
 <section className="dash-stat"><span className="dash-stat-icon blue"><DashboardIcon name="calendar"/></span><h2>Agenda Hari Ini</h2><strong>{data?agendas.length:'—'} <span>Agenda</span></strong><div className="dash-stat-list">{agendas.slice(0,2).map(a=><p key={a.id}><span>{a.title}<small>{time(a.startDate)} · {a.location||'Lokasi belum diisi'}</small></span></p>)}{data&&!agendas.length&&<p>Belum ada kegiatan hari ini.</p>}</div><Link to="/agenda">Kelola Agenda</Link></section>
 <section className="dash-stat"><span className="dash-stat-icon teal"><DashboardIcon name="content"/></span><h2>Konten Aktif</h2><strong>{data?data.contents.length:'—'} <span>Konten</span></strong><div className="dash-stat-list">{data?.contents.slice(0,4).map(c=><p key={c.id}>• {c.title||c.type}</p>)}{data&&!data.contents.length&&<p>Belum ada konten aktif.</p>}</div><Link to="/content">Kelola Konten</Link></section></div>
 <section className="dash-panel dash-prayers"><div className="dash-panel-heading"><h2><DashboardIcon name="calendar"/>Jadwal Sholat Hari Ini</h2><span>{data?.mosque.city} · {timezone}</span><Link to="/prayer-settings">Ubah Jadwal</Link></div><div className="dash-prayer-strip">{PRAYERS.map(([key,label,icon])=>{const active=next?.name===key&&next.date===data?.prayer.date;const prayerTime=data?.prayer.effective[key];const nowTime=clock.toLocaleTimeString('en-GB',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'});const passed=prayerTime&&prayerTime<=nowTime;return <div key={key} className={`dash-prayer-tile ${active?'selected':''} ${key}`}><DashboardIcon name={icon}/><div><small>{label.toUpperCase()}</small><strong>{prayerTime||'--:--'}</strong><span>{active?'● Berikutnya':passed?'● Terlewati':'◷ Akan datang'}</span></div></div>})}</div></section>
 <div className="dash-bottom"><section className="dash-panel"><div className="dash-panel-heading"><h2><DashboardIcon name="calendar"/>Agenda Hari Ini</h2><Link to="/agenda">Lihat Semua →</Link></div>{agendas.slice(0,4).map(a=><div className="dash-agenda-row" key={a.id}><time>{time(a.startDate)}</time><div><b>{a.title}</b><small>{a.location||'Lokasi belum diisi'}</small></div></div>)}{!agendas.length&&<div className="dash-empty"><DashboardIcon name="calendar"/><p>Belum ada agenda hari ini</p><Link to="/agenda">Tambah kegiatan mushola →</Link></div>}</section>
 <section className="dash-panel"><div className="dash-panel-heading"><h2><DashboardIcon name="audio"/>Jadwal Audio Berikutnya</h2><Link to="/audio-schedule">Lihat Semua →</Link></div><div className="dash-table-wrap"><table className="dash-audio-table"><thead><tr><th>Waktu</th><th>Nama Audio</th><th>Status</th></tr></thead><tbody>{upcoming.map(item=><tr key={item.id}><td>{time(item.atUtc!)}<small>{new Date(item.atUtc!).toLocaleDateString('id-ID',{timeZone:timezone,day:'numeric',month:'short'})}</small></td><td>{data?.schedules.find(s=>s.id===item.id)?.audio?.name||'Audio'}</td><td><span className="dash-badge">Terjadwal</span></td></tr>)}</tbody></table></div>{!upcoming.length&&<p className="dash-empty">Belum ada jadwal audio aktif.</p>}</section>
 <section className="dash-panel"><div className="dash-panel-heading"><h2><DashboardIcon name="clock"/>Aktivitas Audio Terakhir</h2><Link to="/history">Lihat Semua →</Link></div><div className="dash-timeline">{data?.history.slice(0,5).map(h=><div key={h.id}><i className={`dot ${h.status==='FINISHED'?'online':''}`}/><time>{time(h.startedAt)}<small>{new Date(h.startedAt).toLocaleDateString('id-ID',{timeZone:timezone,day:'numeric',month:'short'})}</small></time><p><b>{h.audioName||'Audio'}</b><small>{STATUS[h.status]||h.status}</small></p></div>)}</div>{!data?.history.length&&<p className="dash-empty">Belum ada riwayat pemutaran.</p>}</section></div>
 <footer className="dash-footer"><img src="/mosque-logo.svg" alt=""/><p>“Sebaik-baik manusia adalah yang bermanfaat bagi orang lain.”<small>(HR. Ahmad)</small></p><span className={error?'dash-offline':''}>● {error?'Koneksi bermasalah':data?'Data terhubung':'Menghubungkan...'}</span><strong>{data?.mosque.name||'Mushola'}<small>Rumah Allah, Rumah Kita</small></strong></footer>
 </div>;
}
