import {Select} from '../components/Select';
import React, { useEffect, useRef, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../contexts/AuthContext';
import './history.css';
interface HistoryItem {id:string;playerDeviceId?:string;audioName?:string;triggerType:string;status:string;startedAt:string;finishedAt?:string;errorMessage?:string}
const STATUSES:Record<string,string>={FINISHED:'Berhasil',ERROR:'Error',STOPPED:'Dihentikan',PLAYING:'Sedang Berjalan',QUEUED:'Antrean'};
export function HistoryPage(){
 const {user}=useAuth();const [items,setItems]=useState<HistoryItem[]>([]),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[timezone,setTimezone]=useState('Asia/Jakarta'),[clock,setClock]=useState(new Date()),[selected,setSelected]=useState<HistoryItem|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 const load=async()=>{setLoading(true);setError('');try{setItems(await api.get<HistoryItem[]>('/history?take=1000'))}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{void load();api.get<{timezone:string}>('/mosque').then(m=>setTimezone(m.timezone)).catch(()=>{});const timer=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(timer)},[]);
 const day=(value:string)=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value));return ['year','month','day'].map(k=>parts.find(p=>p.type===k)?.value).join('-')};
 const invalid=!!from&&!!to&&from>to;
 const scoped=invalid?[]:items.filter(h=>(!from||day(h.startedAt)>=from)&&(!to||day(h.startedAt)<=to)&&[h.audioName,h.playerDeviceId,h.errorMessage].join(' ').toLowerCase().includes(query.toLowerCase()));
 const shown=scoped.filter(h=>!status||h.status===status);
 const date=(value:string)=>new Date(value).toLocaleDateString('id-ID',{timeZone:timezone,day:'numeric',month:'numeric',year:'numeric'});
 const time=(value:string)=>new Date(value).toLocaleTimeString('id-ID',{timeZone:timezone,hourCycle:'h23'});
 const open=(h:HistoryItem)=>{setSelected(h);dialog.current?.showModal()};
 return <div className="history-page"><header><div><small>AUDIO</small><h1>History Playback</h1><p>Riwayat pemutaran audio pada sistem masjid.</p></div><div className="history-date"><b>{clock.toLocaleDateString('id-ID',{timeZone:timezone,weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><small>{clock.toLocaleDateString('id-ID-u-ca-islamic',{timeZone:timezone,day:'numeric',month:'long',year:'numeric'})}</small></div><strong className="history-clock">{time(clock.toISOString()).replaceAll('.',':')}</strong><div className="history-user"><b>{user?.name}</b><small>● Sesi aktif</small></div></header>
 {error&&<div className="alert-error" role="alert">{error}</div>}
 <section className="form-panel"><div className="history-filters"><label>Filter Status<Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{Object.entries(STATUSES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></label><label>Tanggal Mulai<input type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label>Tanggal Selesai<input type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label><input aria-label="Cari audio, catatan, atau player" placeholder="Cari audio, catatan, atau player..." value={query} onChange={e=>setQuery(e.target.value)}/><button type="button" disabled={loading} onClick={()=>void load()}>{loading?'Memuat...':'↻ Refresh'}</button></div>
 {invalid&&<p className="alert-error" role="alert">Tanggal selesai harus sama atau setelah tanggal mulai.</p>}
 <div className="history-stats">{[['','▶','Total Pemutaran'],['FINISHED','✓','Berhasil'],['ERROR','×','Error'],['STOPPED','■','Dihentikan'],['PLAYING','◷','Sedang Berjalan']].map(([key,icon,label])=><div key={key} className={`history-stat ${key.toLowerCase()}`}><span>{icon}</span><div><b>{loading?'—':key?scoped.filter(h=>h.status===key).length:scoped.length}</b><small>{label}</small></div></div>)}</div><p className="hint">Ringkasan mengikuti tanggal dan pencarian, sebelum filter status. Data mencakup maksimal 1.000 pemutaran terbaru; zona waktu {timezone}.</p></section>
 <section className="form-panel"><div className="history-section-heading"><span>◷</span><div><h2>Daftar History Playback</h2><p>Berikut riwayat pemutaran audio pada sistem.</p></div></div><div className="history-table-scroll"><table className="data-table"><thead><tr>{['No','Waktu','Audio','Player','Trigger','Status','Catatan','Aksi'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{shown.map((h,i)=><tr key={h.id}><td>{i+1}</td><td className="history-time">{date(h.startedAt)}<small>{time(h.startedAt)}</small></td><td><div className="history-audio"><span>♫</span><b>{h.audioName||'—'}</b></div></td><td>{h.playerDeviceId||'—'}</td><td><span className={`history-trigger ${h.triggerType.toLowerCase()}`}>{h.triggerType}</span></td><td><span className={`history-status ${h.status.toLowerCase()}`}>{h.status}</span></td><td><div className="history-note" title={h.errorMessage}>{h.errorMessage||'—'}</div></td><td><button type="button" className="secondary" onClick={()=>open(h)}>▤ Detail</button></td></tr>)}{!shown.length&&<tr><td colSpan={8}>{loading?'Memuat riwayat...':'Tidak ada riwayat yang sesuai filter.'}</td></tr>}</tbody></table></div></section>
 <dialog className="history-detail" ref={dialog} aria-labelledby="history-detail-title" onClick={e=>{if(e.target===dialog.current)dialog.current?.close()}}><div className="history-detail-heading"><h2 id="history-detail-title">Detail Pemutaran</h2><button type="button" className="secondary" aria-label="Tutup detail" onClick={()=>dialog.current?.close()}>×</button></div>{selected&&<dl>{[['Audio',selected.audioName||'—'],['Player',selected.playerDeviceId||'—'],['Mulai',`${date(selected.startedAt)} ${time(selected.startedAt)}`],['Selesai',selected.finishedAt?`${date(selected.finishedAt)} ${time(selected.finishedAt)}`:'Belum tercatat'],['Trigger',selected.triggerType],['Status',selected.status],['Catatan',selected.errorMessage||'Tidak ada catatan.']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}</dialog></div>;
}
