import {BrowserPlayer} from '../components/BrowserPlayer';
import {Select} from '../components/Select';
import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { getRealtimeSocket } from '../lib/socket';
import { useAuth } from '../contexts/AuthContext';
import './players.css';
interface Player {id:string;deviceId:string;name:string;status:string;online:boolean;volume:number;lastSeenAt?:string}
interface Audio {id:string;name:string;category:string}
interface History {id:string;audioName?:string;playerDeviceId:string;status:string;startedAt:string;finishedAt?:string;triggerType:string}
const STATUS:Record<string,string>={FINISHED:'Selesai',PLAYING:'Diputar',STOPPED:'Dihentikan',ERROR:'Gagal',QUEUED:'Antrean'};
export function PlayersPage(){
 const {user}=useAuth();const [players,setPlayers]=useState<Player[]>([]),[audios,setAudios]=useState<Audio[]>([]),[history,setHistory]=useState<History[]>([]),[selected,setSelected]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[clock,setClock]=useState(new Date()),[timezone,setTimezone]=useState('Asia/Jakarta');
 const load=async()=>{try{const [p,a,h]=await Promise.all([api.get<Player[]>('/players'),api.get<Audio[]>('/audio?activeOnly=true'),api.get<History[]>('/history?triggerType=MANUAL')]);setPlayers(p);setAudios(a);setHistory(h.filter(row=>row.triggerType==='MANUAL'));}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load();api.get<{timezone:string}>('/mosque').then(m=>setTimezone(m.timezone)).catch(()=>{});const socket=getRealtimeSocket();socket.on('player:status',load);socket.on('playback:update',load);const poll=setInterval(load,20000),tick=setInterval(()=>setClock(new Date()),1000);return()=>{clearInterval(poll);clearInterval(tick);socket.off('player:status',load);socket.off('playback:update',load)}},[]);
 const command=async(p:Player,action:'play'|'stop')=>{if(action==='play'&&!selected[p.deviceId]){setError('Pilih audio terlebih dahulu.');return}setBusy(p.deviceId);setError('');setNotice('');try{await api.post(`/players/${encodeURIComponent(p.deviceId)}/${action}`,action==='play'?{audioId:selected[p.deviceId]}:undefined);setNotice(`Perintah ${action==='play'?'Play':'Stop'} dikirim ke ${p.name}.`);await load()}catch(e){setError((e as Error).message)}finally{setBusy(null)}};
 const date=(value:string)=>new Date(value).toLocaleDateString('id-ID',{timeZone:timezone,day:'numeric',month:'short',year:'numeric'});
 const time=(value:string)=>new Date(value).toLocaleTimeString('id-ID',{timeZone:timezone,hourCycle:'h23'});
 const shown=history.filter(h=>(h.audioName||'').toLowerCase().includes(query.toLowerCase()));
 return <div className="players-page"><header><div><small>▶ AUDIO</small><h1>Player &amp; Play Now</h1><p>Kontrol pemutaran audio secara langsung pada player masjid.</p></div><div className="players-date"><b>{clock.toLocaleDateString('id-ID',{timeZone:timezone,weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><small>{clock.toLocaleDateString('id-ID-u-ca-islamic',{timeZone:timezone,day:'numeric',month:'long',year:'numeric'})}</small></div><strong className="players-clock">{time(clock.toISOString()).replaceAll('.',':')}</strong><div className="players-user"><b>{user?.name}</b><small>● Sesi aktif</small></div></header>
 {error&&<div className="alert-error" role="alert">{error}</div>}{notice&&<div className="alert-success" role="status">{notice}</div>}
 <BrowserPlayer/>
 {players.map(p=><div className="players-control-grid" key={p.id}><section className="form-panel"><h2><span className={`player-led ${p.online?'online':''}`}/>{p.name}</h2><p className="player-device-line">Device: {p.deviceId}<span>Status: <b>{p.status}</b></span></p><label htmlFor={`audio-${p.id}`}>Pilih Audio</label><Select id={`audio-${p.id}`} value={selected[p.deviceId]||''} onChange={e=>setSelected(prev=>({...prev,[p.deviceId]:e.target.value}))}><option value="">Pilih audio dari library...</option>{audios.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</Select>
 <div className="player-preview"><span>Preview di browser</span>{selected[p.deviceId]?<audio key={selected[p.deviceId]} controls preload="metadata" src={`${api.baseUrl}/audio/${selected[p.deviceId]}/file`} onPlay={e=>{const current=e.currentTarget;document.querySelectorAll('audio').forEach(a=>{if(a!==current)a.pause()})}}/>:<p>Pilih audio untuk mendengarkan preview.</p>}</div><div className="form-actions"><button disabled={!p.online||busy!==null||!selected[p.deviceId]} onClick={()=>{document.querySelectorAll('audio').forEach(a=>a.pause());void command(p,'play')}}>▶ Play di Player</button><button className="secondary" disabled={!p.online||busy!==null} onClick={()=>command(p,'stop')}>■ Stop</button></div><p className="hint">Play di Player memutar audio melalui speaker perangkat. Preview hanya diputar di browser ini.</p></section>
 <section className="form-panel player-status-panel"><h2>▣ Status Player</h2><div className={`player-status-banner ${p.online?'online':''}`}><span className={`player-led ${p.online?'online':''}`}/><div><strong>{p.online?'ONLINE':'OFFLINE'}</strong><p>{p.online?'Player terhubung dan siap menerima perintah.':'Player belum terhubung. Jalankan Audio Player Service.'}</p></div></div><dl><div><dt>Nama Device</dt><dd>{p.deviceId}</dd></div><div><dt>Nama Player</dt><dd>{p.name}</dd></div><div><dt>Status</dt><dd>{p.status}</dd></div><div><dt>Volume</dt><dd>{p.volume}%</dd></div>{p.lastSeenAt&&<div><dt>Terakhir Aktif</dt><dd>{date(p.lastSeenAt)} {time(p.lastSeenAt)}</dd></div>}</dl></section></div>)}
 {!players.length&&<section className="form-panel"><h2>Belum ada player terdaftar</h2><p>Aktifkan Audio Browser di atas, atau jalankan Audio Player Service pada perangkat speaker.</p><button className="secondary" onClick={()=>void load()}>↻ Refresh Player</button></section>}
 <section className="form-panel"><div className="players-history-heading"><div><h2>◷ Riwayat Pemutaran (Play Now)</h2><p>Riwayat pemutaran audio secara manual melalui fitur Play Now.</p></div><div className="players-history-filter"><input aria-label="Cari riwayat audio" placeholder="Cari audio..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="secondary" onClick={()=>void load()}>↻ Refresh</button></div></div><div className="players-table-scroll"><table className="data-table"><thead><tr>{['No','Waktu','Audio','Player','Lama Pemutaran','Status'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{shown.map((h,i)=><tr key={h.id}><td>{i+1}</td><td>{date(h.startedAt)}<small>{time(h.startedAt)}</small></td><td><div className="player-history-name"><span>♫</span><b>{h.audioName||'Audio'}</b></div></td><td>{h.playerDeviceId}</td><td>{h.finishedAt?(()=>{const seconds=Math.max(0,Math.floor((Date.parse(h.finishedAt)-Date.parse(h.startedAt))/1000));return [Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0')).join(':')})():'—'}</td><td><span className={`player-history-status ${h.status.toLowerCase()}`}>{STATUS[h.status]||h.status}</span></td></tr>)}{!shown.length&&<tr><td colSpan={6}>Belum ada riwayat yang sesuai.</td></tr>}</tbody></table></div></section></div>;
}
