import {AgendaSlides} from './AgendaSlides';
import {displayBackground} from '../lib/background';
import React,{useEffect,useState} from 'react';
import {Mosque,PrayerToday,Agenda,Content} from '../hooks/useMosqueData';
import {RunningText} from './RunningText';
import {formatGregorian,formatHijri} from '../lib/time';
import './display-layouts.css';
const LABELS:Record<string,string>={fajr:'Subuh',dhuhr:'Dzuhur',asr:'Ashar',maghrib:'Maghrib',isha:'Isya'};
export function DisplayLayouts({contents,mosque,prayer,agendas,running,error,prePrayer}:{contents:Content[];mosque:Mosque|null;prayer:PrayerToday;agendas:Agenda[];running:string;error:string|null;prePrayer:boolean}){
 const [now,setNow]=useState(new Date()),[index,setIndex]=useState(0);const zone=mosque?.timezone||'Asia/Jakarta';
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const timer=setInterval(()=>setIndex(n=>n+1),15000);return()=>clearInterval(timer)},[]);
 const parts=new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(now);const value=(key:string)=>Number(parts.find(p=>p.type===key)?.value||0);const h=value('hour'),m=value('minute'),s=value('second');
 const time=[h,m,s].map(n=>String(n).padStart(2,'0')).join(':');const remaining=prayer.nextPrayer?Math.max(0,Math.ceil((Date.parse(prayer.nextPrayer.atUtc)-now.getTime())/1000)):null;const countdown=remaining===null?'-- : -- : --':[Math.floor(remaining/3600),Math.floor(remaining%3600/60),remaining%60].map(n=>String(n).padStart(2,'0')).join(' : ');
 const localDay=(d:Date)=>d.toLocaleDateString('en-CA',{timeZone:zone});const available=agendas.filter(a=>a.endDate?Date.parse(a.endDate)>now.getTime():localDay(new Date(a.startDate))>=localDay(now));const agenda=available[index%Math.max(1,available.length)];
 const layout=mosque?.displayLayout==='agenda' && mosque?.agendaSlidesEnabled!==false?'digital':mosque?.displayLayout||'digital';const next=<div className="layout-next"><small>{prePrayer?'BERSIAP MENUJU SHOLAT':'SHOLAT BERIKUTNYA'}</small><strong>{prayer.nextPrayer?.label||'Menunggu jadwal'}</strong><b>{countdown}</b><span>JAM · MENIT · DETIK</span></div>;
 return <main style={displayBackground(mosque?.displayBackground)} className={`alternative-display palette-${({mihrab:'emerald',board:'midnight',analog:'midnight',agenda:'emerald'} as Record<string,string>)[layout]||'sapphire'} layout-${layout}`}>
 {error&&<div className="layout-warning">Koneksi terputus — menampilkan data terakhir</div>}
 <AgendaSlides contents={contents} mosqueName={mosque?.name} agendas={agendas} timezone={zone} enabled={mosque?.agendaSlidesEnabled!==false} prayerSeconds={mosque?.prayerSlideSeconds} agendaSeconds={mosque?.agendaSlideSeconds}/>
 <header className="layout-header"><div><img src={mosque?.logo||'/mosque-logo.svg'} alt=""/><section><h1>{mosque?.name||'Mushola'}</h1><p>Rumah Allah, Rumah Kita</p></section></div><section><p>{formatGregorian(zone)}</p><small>{formatHijri(zone)}</small></section></header>
 <section className="layout-stage">
 {layout==='mihrab'?<div className="mihrab-frame"><small>HAYYA 'ALASH SHALAH</small><div className="mihrab-clock">{time}</div>{next}</div>:layout==='panorama'?<><div className="panorama-message"><small>RUMAH ALLAH, RUMAH KITA</small><h2>Mari Sholat<br/>Berjamaah</h2><p>Rapatkan saf, tenangkan hati.</p></div><div className="panorama-time"><strong>{time}</strong>{next}</div></>:layout==='board'?<><div className="board-clock"><small>WAKTU SAAT INI</small><strong>{time}</strong>{next}</div><div className="board-heading"><span>JADWAL SHOLAT</span><small>{mosque?.city} · {zone}</small></div></>:layout==='digital'?<><div className="layout-digital"><small>WAKTU SAAT INI</small><strong>{time}</strong><p>{mosque?.city} · {zone}</p></div>{next}</>:layout==='analog'?<><div className="layout-analog"><svg viewBox="0 0 300 300" role="img" aria-label={`Jam ${time}`}><circle cx="150" cy="150" r="143" className="dial"/>{Array.from({length:60},(_,i)=><line key={i} x1="150" y1="16" x2="150" y2={i%5===0?29:22} transform={`rotate(${i*6} 150 150)`} className={i%5===0?'major':'minor'}/>)}{Array.from({length:12},(_,i)=>{const a=(i+1)*Math.PI/6;return <text key={i} x={150+105*Math.sin(a)} y={150-105*Math.cos(a)} dominantBaseline="middle" textAnchor="middle">{i+1}</text>})}<line className="hand hour" x1="150" y1="150" x2="150" y2="82" transform={`rotate(${(h%12)*30+m*.5} 150 150)`}/><line className="hand minute" x1="150" y1="150" x2="150" y2="49" transform={`rotate(${m*6+s*.1} 150 150)`}/><line className="hand second" x1="150" y1="169" x2="150" y2="38" transform={`rotate(${s*6} 150 150)`}/><circle cx="150" cy="150" r="6" className="dial-center"/></svg><b>{time}</b></div>{next}</>:<><article className="layout-agenda"><small>AGENDA & KAJIAN MUSHOLA</small><h2>{agenda?.title||'Mari Makmurkan Mushola'}</h2>{agenda?<><p>{new Date(agenda.startDate).toLocaleString('id-ID',{timeZone:zone,weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}</p><b>{agenda.location||mosque?.name}</b><p className="layout-agenda-description">{agenda.description}</p><small>{index%available.length+1} / {available.length}</small></>:<p>Belum ada agenda mendatang. Mari menjaga sholat berjamaah dan kebersihan mushola.</p>}</article><aside><div className="layout-small-clock">{time}</div>{next}</aside></>}
 </section>
 <section className="layout-prayer-times">{Object.entries(prayer.effective).map(([key,t])=><div key={key} className={prayer.nextPrayer?.name===key?'selected':''}><span>{LABELS[key]}</span><strong>{t}</strong></div>)}</section>
 {prayer.stale&&<small className="layout-stale">Jadwal cadangan — periksa koneksi API</small>}<RunningText text={running}/>
 </main>;
}

