ALTER TABLE "Mosque" ADD COLUMN "agendaSlidesEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "prayerSlideSeconds" INTEGER NOT NULL DEFAULT 120,
ADD COLUMN "agendaSlideSeconds" INTEGER NOT NULL DEFAULT 60;
