import {PrayerAlarm} from './components/PrayerAlarm';
import {displayBackground} from './lib/background';
import { DisplayLayouts } from './components/DisplayLayouts';
import './themes.css';
import { AgendaSlides } from './components/AgendaSlides';
import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{useMosqueData}from'./hooks/useMosqueData';import{usePhase}from'./hooks/usePhase';import{PrayerGrid}from'./components/PrayerGrid';import{RunningText}from'./components/RunningText';import{formatClock,formatGregorian,formatHijri,todayMinuteToTimestamp}from'./lib/time';import{PrayerKey}from'@mosque/shared-types';
import { DateIcon } from './components/DateIcon';
const LABEL:Record<PrayerKey,string>={fajr:'SUBUH',dhuhr:'DZUHUR',asr:'ASHAR',maghrib:'MAGHRIB',isha:'ISYA'};
function useCountdown(target:number|null){const[p,setP]=useState(['00','00','00']);useEffect(()=>{const tick=()=>{const d=Math.max(0,(target??Date.now())-Date.now());setP([Math.floor(d/3600000),Math.floor((d%3600000)/60000),Math.floor((d%60000)/1000)].map(v=>String(v).padStart(2,'0')))};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[target]);return p}
function showTime(time:string,add=0){const[h,m]=time.split(':').map(Number),t=h*60+m+add,hh=(Math.floor(t/60)+24)%24,mm=(t%60+60)%60;return`${String(hh%12||12).padStart(2,'0')}:${String(mm).padStart(2,'0')} ${hh<12?'AM':'PM'}`}
function useWeather(latitude?:number,longitude?:number){const[w,setW]=useState<{temperature:number;label:string}|null>(null);useEffect(()=>{if(latitude==null||longitude==null)return;const controller=new AbortController();fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&timezone=auto`,{signal:controller.signal}).then(r=>r.json()).then(d=>{const code=Number(d.current?.weather_code),label=code<=1?'Cerah':code<=3?'Cerah Berawan':code<=48?'Berkabut':code<=67?'Hujan':'Berawan';setW({temperature:Math.round(d.current.temperature_2m),label})}).catch(()=>{});return()=>controller.abort()},[latitude,longitude]);return w}
function InfoIcon({type}:{type:'book'|'people'|'heart'}){if(type==='book')return <svg viewBox="0 0 64 64"><path d="M8 15c9-3 17-1 24 5v32c-7-6-15-8-24-5V15Z"/><path d="M56 15c-9-3-17-1-24 5v32c7-6 15-8 24-5V15ZM32 20v32"/><path d="M14 23c5-1 9 0 13 3M14 31c5-1 9 0 13 3M50 23c-5-1-9 0-13 3M50 31c-5-1-9 0-13 3"/></svg>;if(type==='people')return <svg viewBox="0 0 64 64"><circle cx="32" cy="20" r="8"/><circle cx="13" cy="27" r="6"/><circle cx="51" cy="27" r="6"/><path d="M17 52v-8c0-9 6-14 15-14s15 5 15 14v8H17ZM3 51v-7c0-7 4-11 11-11 3 0 5 1 7 2M61 51v-7c0-7-4-11-11-11-3 0-5 1-7 2"/></svg>;return <svg viewBox="0 0 64 64"><path d="M32 53 10 33C-4 19 16 4 32 20 48 4 68 19 54 33L32 53Z"/></svg>}
function App(){const{mosque,prayer,agendas,contents,lastError}=useMosqueData(),timezone=mosque?.timezone||'Asia/Jakarta',phase=usePhase(prayer,timezone),[clock,setClock]=useState(formatClock(timezone));useEffect(()=>{const id=setInterval(()=>setClock(formatClock(timezone)),1000);return()=>clearInterval(id)},[timezone]);const active:PrayerKey=phase.activePrayer??prayer?.nextPrayer?.name??'dhuhr',target=phase.state==='IQOMAH_COUNTDOWN'&&phase.phaseEndMinute!=null?todayMinuteToTimestamp(timezone,phase.phaseEndMinute):prayer?.nextPrayer?new Date(prayer.nextPrayer.atUtc).getTime():null,countdown=useCountdown(target),weather=useWeather(mosque?.latitude,mosque?.longitude);if(!prayer)return <main className="boot-screen">Memuat sistem masjid...</main>;
 const prayerTime=prayer.effective[active];const running=[mosque?.runningText,...contents.filter(c=>c.type==='RUNNING_TEXT').map(c=>c.content)].filter(Boolean).join('   —   ')||'Selamat datang di masjid kami',quote=contents.find(c=>c.type==='QURAN'||c.type==='HADITH');
 if(['ADHAN','IQOMAH_COUNTDOWN','PRAYER'].includes(phase.state)){const heading=phase.state==='ADHAN'?'SEDANG ADZAN':phase.state==='IQOMAH_COUNTDOWN'?'IQAMAH':'SEDANG SHOLAT';return <PrayerAlarm name={mosque?.name||'Mushola'} logo={mosque?.logo} heading={heading} prayer={LABEL[phase.activePrayer??active]} time={prayer.effective[phase.activePrayer??active]} countdown={phase.state==='IQOMAH_COUNTDOWN'?countdown.join(' : '):undefined}/> }
 if (mosque?.displayLayout && mosque.displayLayout !== 'classic') return <DisplayLayouts contents={contents} mosque={mosque} prayer={prayer} agendas={agendas} running={running} error={lastError} prePrayer={phase.state === 'PRE_PRAYER'}/>;
 const defaults:[('book'|'people'|'heart'),string,string][]=[['book','Kajian Rutin','Setiap malam Jumat setelah Sholat Isya'],['people','Mari Berjamaah','Sholat berjamaah lebih utama daripada sholat sendirian'],['heart','Jaga Kebersihan Masjid','Masjid yang bersih, nyaman untuk semua jamaah']];return <main style={displayBackground(mosque?.displayBackground, true)} className={`dashboard theme-${'sapphire'} ${displayBackground(mosque?.displayBackground, true)?'has-scene':''}`}>{lastError&&<div className="connection-banner">⚠ Koneksi server terputus — menampilkan data terakhir</div>}<header className="topbar"><section className="brand"><div className="brand-mark" style={mosque?.logo ? { backgroundImage: `url("${mosque.logo}")` } : undefined}>🕌</div><div><h1>{mosque?.name||'Masjid Al Uthman'}</h1><p>Rumah Allah, Rumah Kita</p></div></section><section className="date-block"><p><DateIcon/><span>{formatGregorian(timezone)}</span></p><p><DateIcon hijri/><span>{formatHijri(timezone)}</span></p></section><section className="clock-block"><strong>{clock}</strong><p>Mari Lebih Dekat dengan Allah</p></section><section className="allah-mark"><b>الله</b><span>LEBIH<br/>DEKAT<br/>DENGAN<br/>ALLAH</span></section></header>
 <AgendaSlides contents={contents} mosqueName={mosque?.name} agendas={agendas} timezone={timezone} prayer={prayer} enabled={mosque?.agendaSlidesEnabled !== false} prayerSeconds={mosque?.prayerSlideSeconds} agendaSeconds={mosque?.agendaSlideSeconds}/><section className="hero-row"><article className="next-card"><p>Sholat Berikutnya</p><h2>{LABEL[active]}</h2><div className="countdown"><img className="sun" src="/countdown-sun.svg" alt="" aria-hidden="true"/>{countdown.map((v,i)=><React.Fragment key={i}><div><b>{v}</b><small>{['JAM','MENIT','DETIK'][i]}</small></div>{i<2&&<i>:</i>}</React.Fragment>)}</div><div className="times"><div><img className="adhan-icon" src="/adhan-speaker.svg" alt="" aria-hidden="true"/><p>Adzan<strong>{showTime(prayerTime)}</strong></p></div><div><span>♟</span><p>Iqamah<strong>{showTime(prayerTime,prayer.iqomah[active])}</strong></p></div></div><blockquote>{quote?.content||'“Dirikanlah sholat, sesungguhnya sholat mencegah dari perbuatan keji dan mungkar.”'}<small>{quote?.title||'(QS. Al-‘Ankabut : 45)'}</small></blockquote></article><PrayerGrid effective={prayer.effective} active={active}/></section>
 <section className="info-strip">{[0,1,2].map(i=>{const item=agendas[i];return <article key={i}><span><InfoIcon type={defaults[i][0]}/></span><div><b>{item?.title||defaults[i][1]}</b><p>{item?`${new Date(item.startDate).toLocaleDateString('id-ID')} ${item.location||''}`:defaults[i][2]}</p></div><i>›</i></article>})}</section><RunningText text={running}/><aside className="weather"><img className="weather-icon" src="/weather-partly-cloudy.svg" alt="" aria-hidden="true"/><b>{weather?`${weather.temperature}°C`:'--°C'}</b><div className="weather-details"><span>{weather?.label||'Memuat cuaca'}</span><small>{mosque?.city||'Bekasi'}, {mosque?.province||'Jawa Barat'}</small></div></aside></main>}
createRoot(document.getElementById('root')!).render(<App/>);




